# Generated by Django 6.0.2 on 2026-02-10 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0002_data_models'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='auditevent',
            new_name='vault_audit_organiz_d112bb_idx',
            old_name='vault_audite_organiz_42f2c2_idx',
        ),
        migrations.RenameIndex(
            model_name='auditevent',
            new_name='vault_audit_actor_i_da2e4d_idx',
            old_name='vault_audite_actor_i_07d13d_idx',
        ),
        migrations.RenameIndex(
            model_name='scopekey',
            new_name='vault_scope_scope_b4a1e8_idx',
            old_name='vault_scopek_scope_8f5a5a_idx',
        ),
        migrations.RenameIndex(
            model_name='vaultitem',
            new_name='vault_vault_organiz_7a1207_idx',
            old_name='vault_vault_organiz_f4a5c1_idx',
        ),
        migrations.RenameIndex(
            model_name='vaultitem',
            new_name='vault_vault_owner_i_7a91e8_idx',
            old_name='vault_vault_owner_i_16f6d7_idx',
        ),
    ]
