# Generated by Django 6.0.2 on 2026-05-27 18:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_user_last_mfa_login_user_totp_secret"),
        (
            "vault",
            "0003_rename_vault_audite_organiz_42f2c2_idx_vault_audit_organiz_d112bb_idx_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="auditevent",
            index=models.Index(
                fields=["target_type", "target_id"],
                name="vault_audit_target__e11436_idx",
            ),
        ),
    ]
