# Generated by Django 6.0.2 on 2026-05-20 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_adminconfig"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="last_mfa_login",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="totp_secret",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
